- include: toolchain/setup.yml
- include: ssl/setup.yml
- include: ssl/master.yml
- include: ssl/build.yml
- include: cluster/etcd.yml
- include: cluster/master.yml
- include: cluster/node.yml
# TODO We should wait for API and registering every node (approx.: 1 Minute)
- include: cluster/canal.yml
# TODO We should wait for Canal initialization (approx.: 5-7 Minutes)
- include: addons/setup.yml
# TODO We should wait for Helm Tiller initialization (approx.: 1 Minute)
- include: cluster/build.yml
